# Generated by Django 5.0.1 on 2024-01-10 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0003_emaildata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildata',
            old_name='email',
            new_name='to_email',
        ),
    ]
