# Generated by Django 5.0.1 on 2024-01-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0004_rename_email_emaildata_to_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaildata',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emaildata',
            name='lastname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
