# Generated by Django 5.0.1 on 2024-01-11 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0005_emaildata_firstname_emaildata_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildata',
            old_name='to_email',
            new_name='email',
        ),
    ]
