# Generated by Django 5.0.1 on 2024-01-12 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0007_rename_email_emaildata_from_email_emaildata_to_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emaildata',
            old_name='from_email',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='emaildata',
            name='to_email',
        ),
    ]
