# Generated by Django 5.0.1 on 2024-01-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageuploadapp', '0008_rename_from_email_emaildata_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaildata',
            name='firstname',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='lastname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='emaildata',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
